[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
actix-web = "3"
actix-files = "0.5"
log = "0.4"
simple_logger = "1.13"