# Generated by Django 3.2.6 on 2021-08-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='atLab',
            field=models.BooleanField(default=False),
        ),
    ]
