# Generated by Django 3.2.6 on 2021-08-20 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_student_atlab'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastLoggedIn',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
