# Generated by Django 3.2.6 on 2021-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0003_student_lastloggedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='totalTime',
            field=models.FloatField(default=0),
        ),
    ]
