# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursworked',
            name='newTimeIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursworked',
            name='newTimeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
