# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_auto_20200110_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sudo',
            field=models.BooleanField(default=False),
        ),
    ]
