# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0004_auto_20180615_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='averagePercentTimeWeighted',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='stddevPercentTimeWeighted',
            field=models.FloatField(default=0),
        ),
    ]
