# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0005_auto_20180616_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursWorkedEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newTimeIn', models.DateTimeField()),
                ('newTimeOut', models.DateTimeField()),
                ('hours', models.ForeignKey(default=b'None', on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.HoursWorked')),
            ],
        ),
        migrations.CreateModel(
            name='HoursWorkedEditSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursWorkedEdit', models.ManyToManyField(blank=True, to='attendanceapp.HoursWorkedEdit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.Student')),
            ],
        ),
    ]
