# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0007_hoursworkededit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursworkededit',
            name='newTimeIn',
        ),
        migrations.RemoveField(
            model_name='hoursworkededit',
            name='newTimeOut',
        ),
        migrations.AddField(
            model_name='hoursworked',
            name='newTimeIn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hoursworked',
            name='newTimeOut',
            field=models.DateTimeField(null=True),
        ),
    ]
