# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0008_auto_20181217_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursworkededit',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='hoursworkededit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='hoursworkededitset',
            name='hoursWorkedEdit',
        ),
        migrations.AddField(
            model_name='hoursworkededitset',
            name='contents',
            field=models.ManyToManyField(blank=True, to='attendanceapp.HoursWorked'),
        ),
        migrations.DeleteModel(
            name='HoursWorkedEdit',
        ),
    ]
