# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0009_auto_20181217_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursworkededitset',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
